### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by cosi1**

### CODE REVIEW

**Comment by jcubic** [comment]
There should be license information in readme and copyright note.

**Comment by cosi1** [comment]
@jcubic That's not true, actually. MIT license doesn't require you to put license information anywhere outside LICENSE file. The same is true for the copyright notice.

**Comment by jcubic** [comment]
But it's good practice to have the note in the README so it's easier to read.

**Comment by cosi1** [comment]
@jcubic It is, but we got complaints about it from the users. Besides that, in the README we had a weird license name, different from MIT and not explained.

**Pull request merged**
